### ISSUE TITLE
Wonky audio volume is back..

### ISSUE THREAD

**Issue by smoothuk** [modestimpala/OdinOnDemand#22] opened 2024-03-16 13:53 UTC
But this time there's no Radio nearby.  Not sure what's causing it, but it seems to happen after you adjust the Master Volume.  Will let you know if I discover anything relevant.

Not sure if this is anything to do with it, but this error pops up sometimes when trying to link a speaker to a screen-

> [Error  : Unity Log] NullReferenceException
Stack trace:
OdinOnDemand.Components.SpeakerHelper.CompressSpeakerList (System.Collections.Generic.HashSet`1[T] speakers) (at <90dd2a6afabd45f9a325b894a78fa5d7>:0)
OdinOnDemand.MPlayer.BasePlayer.SaveZDO (System.Boolean saveTime) (at <90dd2a6afabd45f9a325b894a78fa5d7>:0)
OdinOnDemand.Components.MediaPlayerComponent.SaveZDO (System.Boolean saveTime) (at <90dd2a6afabd45f9a325b894a78fa5d7>:0)
OdinOnDemand.MPlayer.BasePlayer.AddSpeaker (OdinOnDemand.Components.SpeakerComponent sp) (at <90dd2a6afabd45f9a325b894a78fa5d7>:0)
OdinOnDemand.Components.RemoteControlItem.ProcessRaycast () (at <90dd2a6afabd45f9a325b894a78fa5d7>:0)
OdinOnDemand.Components.RemoteControlItem.Update () (at <90dd2a6afabd45f9a325b894a78fa5d7>:0)

> 

Edit: I had trouble reproducing this issue on a new world, so I've uploaded my world where it's happening (it is slightly too big to attach).

[https://www.dropbox.com/scl/fi/29qu9qco6f5xwk6hiz7vc/ood.zip?rlkey=zvkt2huwgzwy3z5v90as5gfo8&dl=0](https://www.dropbox.com/scl/fi/29qu9qco6f5xwk6hiz7vc/ood.zip?rlkey=zvkt2huwgzwy3z5v90as5gfo8&dl=0)

**Comment by modestimpala** [comment] 2024-03-17 03:25
Thanks for the report smoothuk! The save file for bug reproduction is also highly appreciated. 👍 

Looks like it was the Receiver asset this time, I have the incorrect mixer set on the prefab just like the radio. Whoops.
I saw you had one placed 
![image](https://github.com/modestimpala/OdinOnDemand/assets/45338507/4aba5f4c-e547-4323-a856-16aa00eff442)
So I destroyed it and the bug stopped. I'll have that fixed in the next version.

Are you able to provide more information on reproducing the speaker issue? I haven't had that yet, and I tried linking a few speakers on your map and it seemed to work fine. If you figure out more info please let me know.

Regards
Moddy

**Closed** 2024-03-17 03:28 UTC
Labels: bug

**Comment by smoothuk** [comment] 2024-03-17 09:10
All I can say about the speaker thing is, it happened when I tried to link a speaker to the theater screen.  Instead of saying "Speaker linked", no message was displayed in game but instead the error message appeared in console.  I also couldn't reproduce this on a new world, and had trouble getting the error consistently on the world I sent you.
